
// This file has been generated by the GUI designer. Do not modify.
namespace barCodeGenerator
{
	public partial class codebarGenerator
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HPaned hpan;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Alignment alignment5;
		
		private global::Gtk.ComboBox cmbBarCodeType;
		
		private global::Gtk.HBox hbox11;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Alignment alignment4;
		
		private global::Gtk.Entry txtData;
		
		private global::Gtk.HBox hbox12;
		
		private global::Gtk.Alignment alignment6;
		
		private global::Gtk.Button btnGenerar;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.ComboBox cmbColorText;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.ComboBox cmbColorBackground;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Entry txtWidth;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Alignment alignment7;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Entry txtHeight;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.CheckButton chkIncludeLabel;
		
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.ComboBox cmbTextPosition;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.Image imgCodeBar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget barCodeGenerator.codebarGenerator
			this.Name = "barCodeGenerator.codebarGenerator";
			this.Title = global::Mono.Unix.Catalog.GetString ("Generador de códigos de barras");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-convert", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child barCodeGenerator.codebarGenerator.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hpan = new global::Gtk.HPaned ();
			this.hpan.CanFocus = true;
			this.hpan.Name = "hpan";
			this.hpan.Position = 292;
			// Container child hpan.Gtk.Paned+PanedChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(3));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Típo de Código de Barras");
			this.hbox10.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.hbox10.Add (this.alignment5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.alignment5]));
			w2.Position = 1;
			this.vbox3.Add (this.hbox10);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox10]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.cmbBarCodeType = global::Gtk.ComboBox.NewText ();
			this.cmbBarCodeType.Name = "cmbBarCodeType";
			this.vbox3.Add (this.cmbBarCodeType);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.cmbBarCodeType]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Texto a generar");
			this.label2.UseMarkup = true;
			this.label2.Wrap = true;
			this.hbox11.Add (this.label2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.hbox11.Add (this.alignment4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.alignment4]));
			w6.Position = 1;
			this.vbox3.Add (this.hbox11);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox11]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.txtData = new global::Gtk.Entry ();
			this.txtData.CanFocus = true;
			this.txtData.Name = "txtData";
			this.txtData.IsEditable = true;
			this.txtData.InvisibleChar = '●';
			this.vbox3.Add (this.txtData);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.txtData]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.hbox12.Add (this.alignment6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.alignment6]));
			w9.Position = 0;
			// Container child hbox12.Gtk.Box+BoxChild
			this.btnGenerar = new global::Gtk.Button ();
			this.btnGenerar.CanFocus = true;
			this.btnGenerar.Name = "btnGenerar";
			this.btnGenerar.UseUnderline = true;
			this.btnGenerar.Label = global::Mono.Unix.Catalog.GetString ("Generar código de barras");
			this.hbox12.Add (this.btnGenerar);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.btnGenerar]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox3.Add (this.hbox12);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox12]));
			w11.Position = 4;
			w11.Expand = false;
			w11.Fill = false;
			this.hpan.Add (this.vbox3);
			global::Gtk.Paned.PanedChild w12 = ((global::Gtk.Paned.PanedChild)(this.hpan [this.vbox3]));
			w12.Resize = false;
			// Container child hpan.Gtk.Paned+PanedChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(9));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Color de texto");
			this.hbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label3]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cmbColorText = global::Gtk.ComboBox.NewText ();
			this.cmbColorText.Name = "cmbColorText";
			this.hbox1.Add (this.cmbColorText);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cmbColorText]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Color de fondo");
			this.hbox2.Add (this.label4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label4]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.cmbColorBackground = global::Gtk.ComboBox.NewText ();
			this.cmbColorBackground.Name = "cmbColorBackground";
			this.hbox2.Add (this.cmbColorBackground);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cmbColorBackground]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			this.hbox9.BorderWidth = ((uint)(3));
			// Container child hbox9.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Ancho");
			this.hbox9.Add (this.label6);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label6]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.txtWidth = new global::Gtk.Entry ();
			this.txtWidth.WidthRequest = 42;
			this.txtWidth.CanFocus = true;
			this.txtWidth.Name = "txtWidth";
			this.txtWidth.Text = global::Mono.Unix.Catalog.GetString ("200");
			this.txtWidth.IsEditable = true;
			this.txtWidth.WidthChars = 0;
			this.txtWidth.MaxLength = 3;
			this.txtWidth.InvisibleChar = '●';
			this.hbox9.Add (this.txtWidth);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.txtWidth]));
			w20.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("px");
			this.hbox9.Add (this.label8);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label8]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment7.WidthRequest = 10;
			this.alignment7.Name = "alignment7";
			this.hbox9.Add (this.alignment7);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.alignment7]));
			w22.Position = 3;
			w22.Expand = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("px");
			this.hbox9.Add (this.label9);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label9]));
			w23.PackType = ((global::Gtk.PackType)(1));
			w23.Position = 4;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.txtHeight = new global::Gtk.Entry ();
			this.txtHeight.WidthRequest = 42;
			this.txtHeight.CanFocus = true;
			this.txtHeight.Name = "txtHeight";
			this.txtHeight.Text = global::Mono.Unix.Catalog.GetString ("200");
			this.txtHeight.IsEditable = true;
			this.txtHeight.InvisibleChar = '●';
			this.hbox9.Add (this.txtHeight);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.txtHeight]));
			w24.PackType = ((global::Gtk.PackType)(1));
			w24.Position = 5;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Alto");
			this.hbox9.Add (this.label7);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label7]));
			w25.PackType = ((global::Gtk.PackType)(1));
			w25.Position = 6;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox1.Add (this.hbox9);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox9]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.chkIncludeLabel = new global::Gtk.CheckButton ();
			this.chkIncludeLabel.CanFocus = true;
			this.chkIncludeLabel.Name = "chkIncludeLabel";
			this.chkIncludeLabel.Label = global::Mono.Unix.Catalog.GetString ("Incluir etiqueta");
			this.chkIncludeLabel.Active = true;
			this.chkIncludeLabel.DrawIndicator = true;
			this.chkIncludeLabel.UseUnderline = true;
			this.hbox3.Add (this.chkIncludeLabel);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.chkIncludeLabel]));
			w27.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.WidthRequest = 20;
			this.alignment1.Name = "alignment1";
			this.hbox3.Add (this.alignment1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment1]));
			w28.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Posición del Texto");
			this.hbox3.Add (this.label5);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label5]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.cmbTextPosition = global::Gtk.ComboBox.NewText ();
			this.cmbTextPosition.Name = "cmbTextPosition";
			this.hbox3.Add (this.cmbTextPosition);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.cmbTextPosition]));
			w30.Position = 3;
			w30.Expand = false;
			w30.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w31.Position = 3;
			w31.Expand = false;
			w31.Fill = false;
			this.hpan.Add (this.vbox1);
			this.vbox2.Add (this.hpan);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hpan]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w34 = new global::Gtk.Viewport ();
			w34.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.imgCodeBar = new global::Gtk.Image ();
			this.imgCodeBar.Name = "imgCodeBar";
			w34.Add (this.imgCodeBar);
			this.GtkScrolledWindow.Add (w34);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w37.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 716;
			this.DefaultHeight = 551;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.btnGenerar.Clicked += new global::System.EventHandler (this.OnBtnGenerarClicked);
			this.chkIncludeLabel.Toggled += new global::System.EventHandler (this.OnChkIncludeLabelToggled);
		}
	}
}
